events {
    worker_connections 1024;
}

http {
    # Настройка зоны кэширования:
    # keys_zone=reports_cache:10m - выделяем 10 МБ в ОЗУ под ключи
    # max_size=1g                 - максимальный размер кэша на диске
    # inactive=7d                 - удалять файлы, которые не запрашивали 7 дней
    proxy_cache_path /var/cache/nginx levels=1:2 keys_zone=reports_cache:10m max_size=1g inactive=7d use_temp_path=off;

    server {
        listen 80;

        # Роут для скачивания отчетов из эмулированного CDN
        location /cdn/ {
            # Убираем префикс /cdn/ перед отправкой запроса в MinIO
            # Запрос http://localhost:8085/cdn/file.json уйдет в MinIO как http://minio:9000/reports/file.json
            rewrite ^/cdn/(.*)$ /reports/$1 break;

            # Проксируем запрос к S3 API MinIO
            proxy_pass http://minio:9000;

            # Включаем кэширование, используем зону, описанную выше
            proxy_cache reports_cache;

            # Кэшируем успешные ответы (200) на 7 дней
            proxy_cache_valid 200 7d;

            # Игнорируем заголовки MinIO, заставляя Nginx кэшировать принудительно
            proxy_ignore_headers Cache-Control Expires;

            # Разрешаем Nginx отдавать старый кэш, если MinIO вдруг упал
            proxy_cache_use_stale error timeout http_500 http_502 http_503 http_504;

            # Добавляем заголовок в ответ, чтобы в браузере видеть, попали мы в кэш (HIT) или нет (MISS)
            add_header X-Cache-Status $upstream_cache_status;
        }
    }
}